# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Init
        run: |
          go mod tidy
          sudo ln $JAVA_HOME/include/jni.h /usr/local/include 
          sudo ln $JAVA_HOME/include/linux/jni_md.h /usr/local/include 
          sudo ln $JAVA_HOME/lib/server/libjvm.so /usr/local/lib


      - name: Build
        run: go build -v ./...

      - name: Test
        run: |
          go test ./config/test
          go test ./isc/test
          go test ./validate/test
          go test ./compress/test
          go test ./cron/test
          go test ./encoding/test
          go test ./file/test
          go test ./goid/test
          go test ./i18n/test
          go test ./coder/test
          go test ./time/test
          go test ./listener/test
          go test ./bean/test

